### PR TITLE
test adding name to contributors.md

### PR DESCRIPTION
**Pull request by Roshanjossey**

### CODE REVIEW

**Comment by Roshanjossey** [comment]
@Esh07, can you change workflow settings such that it doesn't need maintainer approval?

**Comment by Esh07** [comment]
@Roshanjossey I have updated the setting 
image

**Comment by Roshanjossey** [comment]
403 gives me the feeling that the token used in auth (I'm thinking it's `GITHUB_TOKEN`) doesn't have the privilages for merging a PR from an external contributor.

> RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/actions/github-script/v5/dist/index.js:4560:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4888:56), <anonymous>:2:18)
    at async main (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4943:20) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/Esh07/first-contributions/pulls/23/merge',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Wed, 14 Jun 2023 22:48:19 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3',
      'x-github-request-id': 'BC82:7126:1A3A9A7:3573164:648A43B3',
      'x-ratelimit-limit': '1000',
      'x-ratelimit-remaining': '999',
      'x-ratelimit-reset': '1686786499',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '1',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/reference/pulls#merge-a-pull-request'
    }
  },
  request: {
    method: 'PUT',
    url: 'https://api.github.com/repos/Esh07/first-contributions/pulls/23/merge',
    headers: {
      accept: 'application/vnd.github.-preview+json',
      'user-agent': 'actions/github-script octokit-core.js/3.5.1 Node.js/12.22.7 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"merge_method":"squash"}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
}

**Comment by Esh07** [comment]
> 403 gives me the feeling that the token used in auth (I'm thinking it's `GITHUB_TOKEN`) doesn't have the privilages for merging a PR from an external contributor.
> 
> > RequestError [HttpError]: Resource not accessible by integration
> > at /home/runner/work/_actions/actions/github-script/v5/dist/index.js:4560:21
> > at processTicksAndRejections (internal/process/task_queues.js:97:5)
> > at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4888:56), :2:18)
> > at async main (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4943:20) {
> > status: 403,
> > response: {
> > url: 'https://api.github.com/repos/Esh07/first-contributions/pulls/23/merge',
> > status: 403,
> > headers: {
> > 'access-control-allow-origin': '*',
> > 'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
> > connection: 'close',
> > 'content-encoding': 'gzip',
> > 'content-security-policy': "default-src 'none'",
> > 'content-type': 'application/json; charset=utf-8',
> > date: 'Wed, 14 Jun 2023 22:48:19 GMT',
> > 'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
> > server: 'GitHub.com',
> > 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
> > 'transfer-encoding': 'chunked',
> > vary: 'Accept-Encoding, Accept, X-Requested-With',
> > 'x-content-type-options': 'nosniff',
> > 'x-frame-options': 'deny',
> > 'x-github-api-version-selected': '2022-11-28',
> > 'x-github-media-type': 'github.v3',
> > 'x-github-request-id': 'BC82:7126:1A3A9A7:3573164:648A43B3',
> > 'x-ratelimit-limit': '1000',
> > 'x-ratelimit-remaining': '999',
> > 'x-ratelimit-reset': '1686786499',
> > 'x-ratelimit-resource': 'core',
> > 'x-ratelimit-used': '1',
> > 'x-xss-protection': '0'
> > },
> > data: {
> > message: 'Resource not accessible by integration',
> > documentation_url: 'https://docs.github.com/rest/reference/pulls#merge-a-pull-request'
> > }
> > },
> > request: {
> > method: 'PUT',
> > url: 'https://api.github.com/repos/Esh07/first-contributions/pulls/23/merge',
> > headers: {
> > accept: 'application/vnd.github.-preview+json',
> > 'user-agent': 'actions/github-script octokit-core.js/3.5.1 Node.js/12.22.7 (linux; x64)',
> > authorization: 'token [REDACTED]',
> > 'content-type': 'application/json; charset=utf-8'
> > },
> > body: '{"merge_method":"squash"}',
> > request: { agent: [Agent], hook: [Function: bound bound register] }
> > }
> > }

maybe i forgot to tick checkbox 
image

**Comment by Roshanjossey** [comment]
0ne suggestion for testing this workflow: Create another GitHub account that doesn't have any privileges in this repo. Try PRs with that account. That'll correctly replicate what would happen in real life.

**Comment by Esh07** [comment]
> 0ne suggestion for testing this workflow: Create another GitHub account that doesn't have any privileges in this repo. Try PRs with that account. That'll correctly replicate what would happen in real life.

Alright. I will use another account to simulate the process to see if it still failing.

**Comment by Esh07** [comment]
I tried re-running all the failed jobs but it's all running on old script. Please create a new PR and test it. I hope it should work now.

**Comment by Roshanjossey** [comment]
@Esh07, it doesn't work for me.
Did you try testing it with another account? Are there any PRs that got merged automatically like that?

**Pull request closed without merging**
